### ISSUE TITLE
[bug]: Not automatically delete $ZPFX/bin files

### ISSUE THREAD

**Issue by karbobc** [zdharma-continuum/zinit-annex-bin-gem-node#13]
### Describe the bug

Not automatically delete `$ZPFX/bin` files when using `zinit delete --all` to delete all the installed plugins

### Steps to reproduce

1. install `exa` plugin
```shell
zinit ice wait lucid id-as nocompile \
  from="gh-r" \
  sbin="bin/exa -> exa" \
  atclone="cp -vf completions/exa.zsh _exa_completion && ln -sfv \$PWD/man/exa.1 $ZINIT[MAN_DIR]/man1" \
  atpull="%atclone" 
  if="(( ! ${+commands[exa]} ))"
zinit light ogham/exa
```
2. delete all the plugins included `exa`
```shell
zinit delete --all
```

### Expected behavior

`bin-gem-node annex: Correctly removed the exa shim from $ZPFX/bin`

### Operating System & Version

linux-gnu |  | x86_64-pc-linux-gnu |  | x86_64 x86_64

### Zsh version

zsh 5.8 (x86_64-ubuntu-linux-gnu)

### Terminal emulator

xterm-256color

**Comment by vladdoster** [comment]
@karbobc,

This has been fixed.

<img width="841" alt="Screenshot 2023-11-30 at 19 03 11" src="https://github.com/zdharma-continuum/zinit-annex-bin-gem-node/assets/10052309/4a49339b-228a-47b4-bcfa-74ce42eeac93">

**Comment by vladdoster** [comment]
@karbobc,

Fixed in https://github.com/zdharma-continuum/zinit/pull/612

<img width="1728" alt="Screenshot 2023-12-24 at 08 47 49" src="https://github.com/zdharma-continuum/zinit-annex-bin-gem-node/assets/10052309/24c390b4-195c-46d0-873e-c594a894129d">

**Comment by karbobc** [comment]
Thank you for fixing this issue!
